version: "3"
services:
  web:
      build: .
      ports:
        - 8080:8080
      env_file:
      - ./.env
      depends_on:
        - db
  db:
    image: postgres:12
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: